---
services:
  whatsup-doc:
    image: ghcr.io/mattboston/whatsup-doc:latest
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # environment:
    #   - HOST_HOSTNAME=${HOSTNAME}
    #   - VERBOSE=true
